name: Auto Lab Tracker Update

on:
  workflow_dispatch: # Button in GitHub Actions to run manually with 1 click!
  push:
    branches: [ main ] # Only runs if you push changes to this python-AM repo

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install gspread google-auth requests

      - name: Write Google Cloud Credentials
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          mkdir -p python-automation/gsheets-automation
          echo "$GCP_SA_KEY" > python-automation/gsheets-automation/credentials.json

      - name: Run Dynamic Lab Tracker
        run: |
          python python-automation/gsheets-automation/35-copy-lab-tracker-automation.py